#!/bin/bash

echo -e "Pre-push Hook"

CURRENT_BRANCH=`git rev-parse --abbrev-ref HEAD`
PROTECTED_BRANCHES="^(main)"

if [[ "$CURRENT_BRANCH" =~ $PROTECTED_BRANCHES ]]
then
  echo -e "\n🚫 Error: Cannot push to remote $CURRENT_BRANCH branch."
  exit 1
fi
