name: Deployment to QA env

on:
  push:
    branches: [main]

permissions:
  contents: read

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  lint:
    strategy:
      matrix:
        node-version: [20.12.2]
    uses: ./.github/workflows/lint.yml
    with:
      node-version: ${{ matrix.node-version }}

  test:
    strategy:
      matrix:
        node-version: [20.12.2]
    needs: [lint]
    uses: ./.github/workflows/test.yml
    with:
      node-version: ${{ matrix.node-version }}

  build-check:
    strategy:
      matrix:
        node-version: [20.12.2]
    needs: [test]
    uses: ./.github/workflows/build.yml
    with:
      node-version: ${{ matrix.node-version }}

  deploy:
    runs-on: ubuntu-latest
    needs: [lint, test, build-check]
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --target=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --target=preview --token=${{ secrets.VERCEL_TOKEN }}
